### ISSUE TITLE
Finetuning with LoRA throws errors

### ISSUE THREAD

**Issue by ConfuseIous** [aisingapore/sealion#5]
Hello,

While trying to train a LoRA for this model, I ran into this error:
`TypeError: MptForCausalLM.forward() got an unexpected keyword argument 'token_type_ids'` 

A minimal reproducible example is available [here](https://github.com/ConfuseIous/SEA-LION-LoRA-MCVE), and you can view the error logs in the train.log file.

I was able to work around this by cloning transformers locally and patching the MPT class. I can provide my changes if this would be helpful.

Would it be possible to get LoRA finetuning supported officially with SEA-LION?

**Comment by yongxb** [comment]
Hello Confuselous,

Thank you for trying out our SEA-LION model and providing feedback on the model. We will look into the error and update you on any progress in due course.

In the meantime, we have an example QLoRA fine-tuning script that can be found here [https://github.com/aisingapore/sealion/tree/main/examples/fine_tuning](https://github.com/aisingapore/sealion/tree/main/examples/fine_tuning). Please try this out and let us know if you encounter any other issues.

Thank you.
